### ISSUE TITLE
Moveer listen to other bots

### ISSUE THREAD

**Issue by ghost** [anderssonoscar0/Moveer#30]
Hi,

can moveer be configured to listen to other bots such as Dyno Bot?

One use case I am trying to create is to create a custom command for Dyno bot such that it can ask Moveer bot to move people with certain roles to a specific breakout room.

If it is not possible, I hope it can be added as a feature in the future.

**Comment by winbergoscar0** [comment]
Moveer already has support for this!
Send us your server ID in the support discord https://discord.gg/dTdH3gD and we'll help you out

//Fragstealern
